name: Run Tests and CodeCov

on: [pull_request]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12"]
        requirements-file: [
          dj42_cms311.txt,
          dj42_cms41.txt,
          dj50_cms41.txt,
          dj51_cms41.txt,
          dj52_cms50.txt,
          dj52.txt,
        ]
        os: [
          ubuntu-latest,
        ]
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install libcairo2-dev pkg-config python3-dev
        python -m pip install --upgrade pip
        python -m pip install -r tests/requirements/${{ matrix.requirements-file }}
        python -m pip install -e .
        npm install
        npx webpack
        playwright install --with-deps

    - name: Run coverage
      run: coverage run -m pytest

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
